### ISSUE TITLE
Add better social icons

### ISSUE THREAD

**Issue by itsff** [itsff/polonijny#26]
Each dictionary entry should have a Facebook like button, Facebook share button, as well as a Twitter button.
These buttons should link back to that specific entry.

**Comment by itsff** [comment]
https://simplesharebuttons.com/html-share-buttons/

**Comment by itsff** [comment]
Include WhatsApp and Wykop as well.

**Comment by chhatrapalsinhzala007** [comment]
Hyy @itsff can I contribute to this ?

**Comment by itsff** [comment]
@chhatrapalsinhzala007 Of course 😊
As you can see, there already are some basic social buttons. But we're still missing "wykop.pl" and other networks. Could also be cool to share the ViewData["description"] as text, for the social networks which allow it.

**Comment by itsff** [comment]
Fixed in #64

**Comment by itsff** [comment]
Fixed in #64
